version: '3.8'
services:
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    #      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/redis/data"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/"
      - "~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq"
    networks:
      - rabbitmq_go_net
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./neo4j/plugins:/plugins"
volumes:
  redis_data:
    driver: local
networks:
  rabbitmq_go_net:
    driver: bridge